language: php

php:
#  - 5.3
#  - 5.4
  - 5.5
#  - 5.6
#  - 7.0

before_script:
  - composer self-update
  - composer global require phpunit/phpunit --no-update
  - composer install
  - echo 'xdebug.max_nesting_level=9999'

script: phpunit -c phpunit.xml
